'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace ORMDataModel1

    Partial Public Class Dongnhap
        Inherits XPObject
        Dim fSanpham_ID As Integer
        Public Property Sanpham_ID() As Integer
            Get
                Return fSanpham_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Sanpham_ID), fSanpham_ID, value)
            End Set
        End Property
        Dim fNhap_ID As Integer
        Public Property Nhap_ID() As Integer
            Get
                Return fNhap_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Nhap_ID), fNhap_ID, value)
            End Set
        End Property
        Dim fSoluong As String
        Public Property Soluong() As String
            Get
                Return fSoluong
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Soluong), fSoluong, value)
            End Set
        End Property
        Dim fDongia As Decimal
        Public Property Dongia() As Decimal
            Get
                Return fDongia
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(Dongia), fDongia, value)
            End Set
        End Property
    End Class

End Namespace
