'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace ORMDataModel1

    Partial Public Class HoadonCT
        Inherits XPObject
        Dim fHoadon_ID As Integer
        Public Property Hoadon_ID() As Integer
            Get
                Return fHoadon_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Hoadon_ID), fHoadon_ID, value)
            End Set
        End Property
        Dim fSanpham_ID As Integer
        Public Property Sanpham_ID() As Integer
            Get
                Return fSanpham_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(Sanpham_ID), fSanpham_ID, value)
            End Set
        End Property
        Dim fSoluong As String
        Public Property Soluong() As String
            Get
                Return fSoluong
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Soluong), fSoluong, value)
            End Set
        End Property
        Dim fDongia As String
        Public Property Dongia() As String
            Get
                Return fDongia
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Dongia), fDongia, value)
            End Set
        End Property
        Dim fThanhtien As Decimal
        Public Property Thanhtien() As Decimal
            Get
                Return fThanhtien
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(Thanhtien), fThanhtien, value)
            End Set
        End Property
    End Class

End Namespace
